"""Every /__host__/ endpoint, over real HTTP.

The unit tests call these functions directly. These go through the server, so
they cover the parts only the server has: routing, the session in the query
string, and the shapes the bridge parses on the other side.
"""

from __future__ import annotations

import json
import shutil
import sys
import urllib.error
import urllib.parse
import urllib.request
from typing import TYPE_CHECKING

import pytest
from support import ScriptedShell

from libera.host import apps, convert, recents, session as sessions
from libera.host.server import BRIDGE_PARTS

if TYPE_CHECKING:
    from b_integration.conftest import LiveHost


def test_current_names_the_open_document(live: LiveHost):
    assert live.json("current")["path"] == str(live.document)


def test_opened_hands_over_the_converted_document(live: LiveHost):
    body = live.json("opened")
    # LocalStartOpen base64-decodes this straight into the editor.
    assert body["len"] == live.host.editor_bin.stat().st_size
    assert len(body["b64"]) > 0


def test_an_unknown_host_route_is_a_404(live: LiveHost):
    assert live.post("no-such-endpoint")[0] == 404


# --- the bridge -------------------------------------------------------------


@pytest.mark.parametrize("part", BRIDGE_PARTS)
def test_each_part_of_the_bridge_is_served(live: LiveHost, part: str):
    assert b"__libera__" in live.get(part)


def test_the_page_is_told_which_keys_the_menu_bar_owns(live: LiveHost):
    """Empty without a window: `libera --serve` has no menu bar to yield to.

    With one, the page yields these so that AppKit is the only thing that acts
    on them -- both ends of File > New make a window.
    """
    assert b"var LIBERA_OWNED_KEYS = [];" in live.get(BRIDGE_PARTS[0])


def test_the_owned_keys_are_the_menu_bar_own_definition(live: LiveHost, monkeypatch):
    """One definition, two readers.

    menu.PAGE_YIELDS builds the menu item *and* feeds the page, so the menu's
    shortcut and the key the page yields cannot drift apart.
    """
    from libera.host import hooks, menu, server

    monkeypatch.setattr(sys, "platform", "darwin")
    monkeypatch.setattr(hooks, "shell", ScriptedShell())

    assert server.list_owned_keys() == [s.as_json() for s in menu.PAGE_YIELDS]
    assert server.list_owned_keys() == [{"key": menu.NEW.key, "shift": False}]


def test_only_the_first_part_carries_the_flags(live: LiveHost):
    """They ride on the first part, which is the one the others depend on."""
    first = live.get(BRIDGE_PARTS[0])
    assert b"var LIBERA_SHOT = " in first
    assert b"var LIBERA_OWNED_KEYS = " in first
    # The names appear in the later parts, which read the flags. Only the
    # declarations are spliced, and only once.
    for part in BRIDGE_PARTS[1:]:
        assert b"var LIBERA_SHOT = " not in live.get(part)
        assert b"var LIBERA_OWNED_KEYS = " not in live.get(part)


def test_every_html_page_gets_the_bridge_spliced_in(live: LiveHost):
    """A page served without it is a blank editor and no error anywhere."""
    page = live.get_static("/web-apps/apps/api/documents/index.html").decode()
    head = page[page.lower().index("<head>") :]
    for part in BRIDGE_PARTS:
        assert f'<script src="/__host__/{part}"></script>' in head
    # The spell wrapper has to be there first: the desktop bundle leaves it out
    # and CSpellchecker must exist before the bridge is asked to check a word.
    assert head.index("/sdkjs/common/spell/spell.js") < head.index(BRIDGE_PARTS[0])


def test_the_spell_wrapper_the_bridge_depends_on_exists(live: LiveHost):
    assert b"CSpellchecker" in live.get_static("/sdkjs/common/spell/spell.js")


def test_slides_can_load_its_themes(live: LiveHost):
    """themes.js and every theme.bin it names.

    Both are generated by payload.sh: sdkjs ships the designs as .pptx and
    nothing else, and the editor asks for themeN/theme.bin by index into
    g_defaultThemes. A missing themes.js is a 404 and an empty theme gallery.
    """
    themes = live.get_static("/sdkjs/slide/themes//themes.js").decode()
    # Past the window["AscCommon"]["g_defaultThemes"] brackets to the array.
    tail = themes.split("g_defaultThemes")[-1]
    names = json.loads(tail[tail.index("[") : tail.rindex("]") + 1])
    assert names, "themes.js names no themes"

    for index in range(1, len(names) + 1):
        binary = live.get_static(f"/sdkjs/slide/themes/theme{index}/theme.bin")
        assert binary, f"theme{index} ({names[index - 1]}) has an empty theme.bin"


def test_dictionaries_are_served(live: LiveHost):
    """The bridge fetches these by hand; they are not in the web bundle."""
    assert live.get_static("/dictionaries/en_US/en_US.aff")


# --- what the editor pushes at us -------------------------------------------


def test_modified_raises_and_clears_the_recovery_marker(live: LiveHost):
    live.post("modified", b'{"modified": true}')
    assert live.host.unsaved_marker.is_file()

    live.post("modified", b'{"modified": false}')
    assert not live.host.unsaved_marker.is_file()


def test_the_editor_reports_what_it_can_do(live: LiveHost):
    """Pushed, not asked for: the menu is validated on the GUI thread."""
    live.post("can", b'{"undo": true, "redo": false}')
    assert sessions.SESSIONS["0"].abilities == {"undo": True, "redo": False}


def test_changes_are_appended_to_the_log_x2t_reads(live: LiveHost):
    """Each chunk arrives raw and is stored as one JSON string, in order."""
    live.post("changes?index=&count=1", b"first")
    live.post("changes?index=&count=1", b"second")

    log = live.host.change_log.path
    assert log.read_text() == '"first","second",'


def test_calls_reports_what_the_page_has_been_doing(live: LiveHost):
    live.post("report", json.dumps({"calls": [{"name": "Ping"}] * 2}).encode())
    assert live.json("calls")["calls"]["Ping"] == 2


# --- what the page is not allowed to talk us into ---------------------------


@pytest.mark.parametrize(
    "url",
    [
        b"file:///etc/passwd",
        b"javascript:alert(1)",
        b"ssh://box/x",
        b"  ",
        b"https://ok.example/ with a space",
    ],
)
def test_open_url_refuses_anything_but_a_bare_http_url(live: LiveHost, url: bytes):
    assert live.post("open-url", url)[0] == 400


def test_open_recent_refuses_a_path_it_never_offered(live: LiveHost):
    assert live.post("open-recent", b'{"id": "/etc/passwd"}')[0] == 404


@pytest.mark.parametrize("name", ["../../../../etc/passwd", "..%2f..%2fpayload.json"])
def test_media_stays_inside_the_media_folder(live: LiveHost, name: str):
    """Asked for the way the editor asks, with a GET. This was a POST, to a
    route that does not exist, so it answered 404 whatever media did."""
    with pytest.raises(urllib.error.HTTPError) as refused:
        live.get(f"media/{name}")

    assert refused.value.code == 404


def test_media_with_a_space_in_its_name_is_served(live: LiveHost):
    """Imported under its own name, and asked for percent-encoded."""
    live.host.media.mkdir(parents=True, exist_ok=True)
    (live.host.media / "My Photo.png").write_bytes(b"\x89PNG picture")

    assert live.get("media/My%20Photo.png") == b"\x89PNG picture"


# --- who may ask at all -----------------------------------------------------
#
# Every page in every browser on this machine can reach 127.0.0.1. Before these
# checks, one from anywhere truncated the open document's change log, and one
# on a rebound DNS name read the document back.

EVIL = "https://evil.example"


def test_a_page_from_another_origin_cannot_touch_the_change_log(live: LiveHost):
    """A text/plain POST is a "simple" request: the browser sends it unasked."""
    live.post("changes?index=&count=1", b"typed")
    log = live.host.change_log.path

    status, _ = live.post(
        "changes?index=0&count=0", session="", headers={"Origin": EVIL}
    )

    assert status == 403
    assert log.read_text() == '"typed",', "another origin rewound the log"


def test_our_own_pages_are_still_let_in(live: LiveHost):
    """The editor's page sends our origin with every POST, and must get through."""
    status, _ = live.post(
        "changes?index=&count=1", b"typed", headers={"Origin": live.url}
    )

    assert status == 204


def test_no_other_site_may_frame_our_pages(live: LiveHost):
    """Framed, the start window's buttons send our origin, which is let in."""
    with urllib.request.urlopen(live.at("start"), timeout=30) as answer:
        policy = answer.headers["Content-Security-Policy"]

    assert policy == "frame-ancestors 'self'"


def test_a_name_rebound_to_this_address_reads_nothing(live: LiveHost):
    """DNS rebinding: the attacker's name, resolving here, makes their page
    same-origin with itself. The Host header is the one thing that gives it
    away."""
    port = live.url.rsplit(":", 1)[1]
    request = urllib.request.Request(
        live.at("current"), headers={"Host": f"evil.example:{port}"}
    )

    with pytest.raises(urllib.error.HTTPError) as refused:
        urllib.request.urlopen(request, timeout=30)

    assert refused.value.code == 403


# --- what a request can carry -----------------------------------------------
#
# Each endpoint read its body where it first needed it, so one it could not
# read raised there and the connection closed with no response at all: the
# editor saw a network fault, and the traceback went past logs.py.


@pytest.mark.parametrize(
    ("route", "body"),
    [
        ("save", b"not json"),
        ("can", b"[1]"),
        ("modified", b"[1]"),
        ("open-recent", b"[]"),
        ("changes?index=abc&count=1", b"x"),
    ],
)
def test_what_an_endpoint_cannot_read_is_a_400(live: LiveHost, route, body):
    assert live.post(route, body)[0] == 400


def test_an_endpoint_that_fails_still_answers(live: LiveHost):
    """The session's files gone from under it, as a sweep would leave them."""
    shutil.rmtree(live.host.doc)

    assert live.post("changes?index=&count=1", b"typed")[0] == 500


def test_a_session_id_outside_latin_1_is_answered(live: LiveHost):
    """Put in the status line, it raised UnicodeEncodeError there instead."""
    with pytest.raises(urllib.error.HTTPError) as refused:
        live.get("current", session=urllib.parse.quote("\u0141"))

    assert refused.value.code == 404


# --- sessions ---------------------------------------------------------------


def test_each_session_answers_for_its_own_document(live: LiveHost, tmp_path):
    """Two windows, two documents: the session decides which one replies."""
    second = tmp_path / "second.docx"
    second.write_bytes(live.document.read_bytes())
    host = sessions.Session(
        payload=live.host.payload, work=tmp_path / "sessions" / "1", document=second
    )
    sessions.configure(host)

    assert live.json("current", session="0")["path"] == str(live.document)
    assert live.json("current", session="1")["path"] == str(second)


def test_a_request_naming_no_session_still_gets_answered(live: LiveHost):
    """Static pages carry no session, and the first one is as good as any."""
    assert live.json("current", session="")["path"] == str(live.document)


def test_a_session_that_has_gone_is_not_answered_for(live: LiveHost):
    """A window that closed may still have a request on its way. It used to
    land on the first session, and an undo index there truncates the wrong
    document's log."""
    live.post("changes?index=&count=1", b"typed")
    log = live.host.change_log.path

    status, _ = live.post("changes?index=0&count=0", session="closed")

    assert status == 404
    assert log.read_text() == '"typed",'


# --- the start window -------------------------------------------------------


def test_the_start_page_is_served(live: LiveHost):
    """Ours, not the payload's: upstream keeps its start screen in C++."""
    page = live.get("start").decode()
    assert "<title>Libera Suite</title>" in page
    assert "__host__/" in page, "the page has no way to reach the host"


def test_the_start_page_reaches_the_host_one_way_only(live: LiveHost):
    """One helper, which throws on a bad status, so nothing can forget to check.

    fetch resolves for 404 and 500; only a network error rejects it. A second
    call site that used fetch directly would be a caller that sees a failure
    as success, which is how the start window came to sit there disabled.
    """
    page = live.get("start").decode()
    assert page.count("fetch(") == 1, "something reaches the host without host()"
    assert "if (!response.ok)" in page, "host() stopped checking the status"


def test_the_start_page_uses_the_editors_own_palette(live: LiveHost):
    """Same token names, same values, taken from the payload's own CSS.

    The start window sits beside the editor, so "aligned" has to mean the
    actual colours and not colours that looked close once. If upstream retunes
    its theme, this is what notices.
    """
    import re

    editor_css = (
        live.host.payload / "web-apps" / "apps" / "documenteditor" / "main" / "app.css"
    ).read_text(errors="replace")
    # The :root block is the default theme -- what the editor renders with
    # until someone changes it.
    root = max(
        (
            m.group(2)
            for m in re.finditer(
                r"\{([^{}]*?)(--background-normal:[^{}]*)\}", editor_css
            )
        ),
        key=len,
    )
    theirs = dict(re.findall(r"(--[a-z-]+):\s*([^;]+)", root))

    page = live.get("start").decode()
    ours = dict(re.findall(r"(--[a-z-]+):\s*([^;]+);", page))

    checked = 0
    for token, value in ours.items():
        if token in theirs:
            assert value.strip() == theirs[token].strip(), (
                f"{token} is {value.strip()} here and {theirs[token].strip()} in the editor"
            )
            checked += 1
    assert checked >= 10, (
        f"only {checked} tokens compared; the page stopped using theirs"
    )


def test_every_new_button_has_a_tile_to_draw(live: LiveHost):
    """An editor that can create has to have a mark, or New draws a blank.

    The page builds each button's icon as `<use href="#tile-{name}">` from the
    name the host handed it. A reference to a symbol that is not there renders
    nothing at all -- no error, no console message, an empty 28px square -- so
    a fifth editor, or a renamed one, would go out looking finished. The brand
    has a tile for three of the four and Diagrams creates nothing, which is the
    only reason this passes today.
    """
    page = live.get("start").decode()
    creates = [app["name"] for app in live.json("apps") if app["creates"]]
    assert creates, "no editor can create anything; the page has nothing to show"
    for name in creates:
        assert f'id="tile-{name}"' in page, f"New offers {name} and has no tile for it"


def test_the_start_page_does_not_follow_the_system_theme(live: LiveHost):
    """Because the editor does not.

    Measured: the editor renders theme-light whatever the OS is set to, and
    persists a theme only once the user changes one. A dark start window beside
    a light editor is worse than no dark mode.
    """
    page = live.get("start").decode()
    assert "@media (prefers-color-scheme" not in page


def test_the_start_page_is_told_which_editors_can_make_something(live: LiveHost):
    listed = {app["name"]: app for app in live.json("apps")}
    assert listed["tables"]["kind"] == "Spreadsheet"
    assert listed["tables"]["doctype"] == "cell"
    # Diagrams is a viewer: offering New for it would promise what x2t refuses.
    assert listed["diags"]["creates"] is False
    assert listed["words"]["creates"] is True


def test_the_start_page_can_say_where_the_payload_came_from(live: LiveHost):
    info = live.json("payload")
    assert info["root"] == str(live.host.payload)
    assert info["origin"]


@pytest.mark.parametrize(
    ("doctype", "suffix"), [("word", ".docx"), ("cell", ".xlsx"), ("slide", ".pptx")]
)
def test_each_kind_starts_from_its_own_blank(live: LiveHost, doctype: str, suffix: str):
    kind = next(a for a in apps.ALL if a.doctype == doctype)
    assert live.host.choose_blank(kind).suffix == suffix


def test_with_no_window_to_open_new_makes_its_own_kind_in_place(live: LiveHost):
    """`libera --serve`: one window, and the new document replaces the old."""
    before = live.host.editor_bin.read_bytes()

    assert live.post("new?type=word")[0] == 200
    # The session's Editor.bin is the only evidence in serve mode -- and it is
    # not empty before either, so what counts is that it changed.
    assert live.host.editor_bin.read_bytes() != before


@pytest.mark.parametrize("doctype", ["cell", "slide"])
def test_with_no_window_to_open_another_kind_is_refused(live: LiveHost, doctype: str):
    """A spreadsheet converted into a Words session left a word processor on
    screen with a spreadsheet's blank behind it. `--serve` has one document and
    one window, so another kind has nowhere to go, and the host says so."""
    assert live.post(f"new?type={doctype}")[0] == 409


# --- opening things ---------------------------------------------------------


def test_opening_a_document_puts_it_in_the_list_the_editor_fetches(live: LiveHost):
    entries = live.json("recents")
    assert [e["path"] for e in entries] == [str(live.document)]
    # id comes straight back to us on open, so it has to be the path.
    assert entries[0]["id"] == entries[0]["path"]


def test_a_listed_document_can_be_opened(live: LiveHost, tmp_path):
    """With no window to open it in, the one window takes it -- `libera --serve`."""
    other = tmp_path / "other.docx"
    other.write_bytes(live.document.read_bytes())
    recents.remember_recent(live.host, other)
    live.host.mark_modified(True)

    status, body = live.post("open-recent", json.dumps({"id": str(other)}).encode())

    assert status == 200
    assert json.loads(body) == {"opened": True, "here": True}
    assert live.json("current")["path"] == str(other)
    # The edits went with the document they were made to; the marker with them.
    assert not live.host.unsaved_marker.is_file()


def test_a_listed_document_that_will_not_open_is_still_answered(
    live: LiveHost, tmp_path, monkeypatch
):
    """Opening it raises, and the request gets an answer, not a dropped line.

    The converter is told to fail rather than handed a broken file: x2t reads
    a broken .docx as plain text and succeeds.
    """
    broken = tmp_path / "broken.docx"
    broken.write_bytes(b"not a document")
    recents.remember_recent(live.host, broken)
    monkeypatch.setattr(convert, "convert_to_editor_bin", lambda *_: False)

    status, body = live.post("open-recent", json.dumps({"id": str(broken)}).encode())

    assert status == 200
    assert json.loads(body) == {"opened": False, "here": True}
    assert live.json("current")["path"] == str(live.document)


def test_file_new_converts_the_blank_the_payload_ships(live: LiveHost):
    before = live.host.editor_bin.read_bytes()

    assert live.post("new")[0] == 200
    assert live.host.editor_bin.read_bytes() != before
