"""Every /__host__/ endpoint, over real HTTP.

The unit tests call these functions directly. These go through the server, so
they cover the parts only the server has: routing, the session in the query
string, and the shapes the bridge parses on the other side.
"""

from __future__ import annotations

import json
import sys
from typing import TYPE_CHECKING

import pytest

from libera.host import apps, recents, session as sessions
from libera.host.server import BRIDGE_PARTS

if TYPE_CHECKING:
    from b_integration.conftest import LiveHost


def test_current_names_the_open_document(live: LiveHost):
    assert live.json("current")["path"] == str(live.document)


def test_opened_hands_over_the_converted_document(live: LiveHost):
    body = live.json("opened")
    # LocalStartOpen base64-decodes this straight into the editor.
    assert body["len"] == live.host.editor_bin.stat().st_size
    assert len(body["b64"]) > 0


def test_an_unknown_host_route_is_a_404(live: LiveHost):
    assert live.post("no-such-endpoint")[0] == 404


# --- the bridge -------------------------------------------------------------


@pytest.mark.parametrize("part", BRIDGE_PARTS)
def test_each_part_of_the_bridge_is_served(live: LiveHost, part: str):
    assert b"__libera__" in live.get(part)


def test_the_page_is_told_which_keys_the_menu_bar_owns(live: LiveHost):
    """Empty without a window: `libera --serve` has no menu bar to yield to.

    With one, the page yields these so that AppKit is the only thing that acts
    on them -- both ends of File > New make a window.
    """
    assert b"var LIBERA_OWNED_KEYS = [];" in live.get(BRIDGE_PARTS[0])


def test_the_owned_keys_are_the_menu_bar_own_definition(live: LiveHost, monkeypatch):
    """One definition, two readers.

    menu.PAGE_YIELDS builds the menu item *and* feeds the page, so the menu's
    shortcut and the key the page yields cannot drift apart.
    """
    from libera.host import hooks, menu, server

    monkeypatch.setattr(sys, "platform", "darwin")
    monkeypatch.setattr(hooks, "WINDOW_OPENER", lambda _document: None)

    assert server.owned_keys() == [s.as_json() for s in menu.PAGE_YIELDS]
    assert server.owned_keys() == [{"key": menu.NEW.key, "shift": False}]


def test_only_the_first_part_carries_the_flags(live: LiveHost):
    """They ride on the first part, which is the one the others depend on."""
    first = live.get(BRIDGE_PARTS[0])
    assert b"var LIBERA_SHOT = " in first
    assert b"var LIBERA_OWNED_KEYS = " in first
    # The names appear in the later parts, which read the flags. Only the
    # declarations are spliced, and only once.
    for part in BRIDGE_PARTS[1:]:
        assert b"var LIBERA_SHOT = " not in live.get(part)
        assert b"var LIBERA_OWNED_KEYS = " not in live.get(part)


def test_every_html_page_gets_the_bridge_spliced_in(live: LiveHost):
    """A page served without it is a blank editor and no error anywhere."""
    page = live.get_static("/web-apps/apps/api/documents/index.html").decode()
    head = page[page.lower().index("<head>") :]
    for part in BRIDGE_PARTS:
        assert f'<script src="/__host__/{part}"></script>' in head
    # The spell wrapper has to be there first: the desktop bundle leaves it out
    # and CSpellchecker must exist before the bridge is asked to check a word.
    assert head.index("/sdkjs/common/spell/spell.js") < head.index(BRIDGE_PARTS[0])


def test_the_spell_wrapper_the_bridge_depends_on_exists(live: LiveHost):
    assert b"CSpellchecker" in live.get_static("/sdkjs/common/spell/spell.js")


def test_slides_can_load_its_themes(live: LiveHost):
    """themes.js and every theme.bin it names.

    Both are generated by payload.sh: sdkjs ships the designs as .pptx and
    nothing else, and the editor asks for themeN/theme.bin by index into
    g_defaultThemes. A missing themes.js is a 404 and an empty theme gallery.
    """
    themes = live.get_static("/sdkjs/slide/themes//themes.js").decode()
    # Past the window["AscCommon"]["g_defaultThemes"] brackets to the array.
    tail = themes.split("g_defaultThemes")[-1]
    names = json.loads(tail[tail.index("[") : tail.rindex("]") + 1])
    assert names, "themes.js names no themes"

    for index in range(1, len(names) + 1):
        binary = live.get_static(f"/sdkjs/slide/themes/theme{index}/theme.bin")
        assert binary, f"theme{index} ({names[index - 1]}) has an empty theme.bin"


def test_dictionaries_are_served(live: LiveHost):
    """The bridge fetches these by hand; they are not in the web bundle."""
    assert live.get_static("/dictionaries/en_US/en_US.aff")


# --- what the editor pushes at us -------------------------------------------


def test_modified_raises_and_clears_the_recovery_marker(live: LiveHost):
    live.post("modified", b'{"modified": true}')
    assert live.host.unsaved.is_file()

    live.post("modified", b'{"modified": false}')
    assert not live.host.unsaved.is_file()


def test_the_editor_reports_what_it_can_do(live: LiveHost):
    """Pushed, not asked for: the menu is validated on the GUI thread."""
    live.post("can", b'{"undo": true, "redo": false}')
    assert sessions.EDITOR_STATE["0"] == {"undo": True, "redo": False}


def test_changes_are_appended_to_the_log_x2t_reads(live: LiveHost):
    """Each chunk arrives raw and is stored as one JSON string, in order."""
    live.post("changes?index=&count=1", b"first")
    live.post("changes?index=&count=1", b"second")

    log = live.host.doc / "changes" / "changes0.json"
    assert log.read_text() == '"first","second",'


def test_calls_reports_what_the_page_has_been_doing(live: LiveHost):
    live.post("report", json.dumps({"calls": [{"name": "Ping"}] * 2}).encode())
    assert live.json("calls")["calls"]["Ping"] == 2


# --- what the page is not allowed to talk us into ---------------------------


@pytest.mark.parametrize(
    "url",
    [
        b"file:///etc/passwd",
        b"javascript:alert(1)",
        b"ssh://box/x",
        b"  ",
        b"https://ok.example/ with a space",
    ],
)
def test_open_url_refuses_anything_but_a_bare_http_url(live: LiveHost, url: bytes):
    assert live.post("open-url", url)[0] == 400


def test_open_recent_refuses_a_path_it_never_offered(live: LiveHost):
    assert live.post("open-recent", b'{"id": "/etc/passwd"}')[0] == 404


@pytest.mark.parametrize("name", ["../../../../etc/passwd", "..%2f..%2fpayload.json"])
def test_media_stays_inside_the_media_folder(live: LiveHost, name: str):
    assert live.post(f"media/{name}")[0] == 404


# --- sessions ---------------------------------------------------------------


def test_each_session_answers_for_its_own_document(live: LiveHost, tmp_path):
    """Two windows, two documents: the session decides which one replies."""
    second = tmp_path / "second.docx"
    second.write_bytes(live.document.read_bytes())
    host = sessions.Host(
        payload=live.host.payload, work=tmp_path / "sessions" / "1", document=second
    )
    sessions.configure(host, "1")

    assert live.json("current", session="0")["path"] == str(live.document)
    assert live.json("current", session="1")["path"] == str(second)


def test_a_request_naming_no_session_still_gets_answered(live: LiveHost):
    """Static pages carry no session, and the first one is as good as any."""
    assert live.json("current", session="")["path"] == str(live.document)


# --- the start window -------------------------------------------------------


def test_the_start_page_is_served(live: LiveHost):
    """Ours, not the payload's: upstream keeps its start screen in C++."""
    page = live.get("start").decode()
    assert "<title>Libera Suite</title>" in page
    assert "__host__/" in page, "the page has no way to reach the host"


def test_the_start_page_reaches_the_host_one_way_only(live: LiveHost):
    """One helper, which throws on a bad status, so nothing can forget to check.

    fetch resolves for 404 and 500; only a network error rejects it. A second
    call site that used fetch directly would be a caller that sees a failure
    as success, which is how the start window came to sit there disabled.
    """
    page = live.get("start").decode()
    assert page.count("fetch(") == 1, "something reaches the host without host()"
    assert "if (!response.ok)" in page, "host() stopped checking the status"


def test_the_start_page_uses_the_editors_own_palette(live: LiveHost):
    """Same token names, same values, taken from the payload's own CSS.

    The start window sits beside the editor, so "aligned" has to mean the
    actual colours and not colours that looked close once. If upstream retunes
    its theme, this is what notices.
    """
    import re

    editor_css = (
        live.host.payload / "web-apps" / "apps" / "documenteditor" / "main" / "app.css"
    ).read_text(errors="replace")
    # The :root block is the default theme -- what the editor renders with
    # until someone changes it.
    root = max(
        (
            m.group(2)
            for m in re.finditer(
                r"\{([^{}]*?)(--background-normal:[^{}]*)\}", editor_css
            )
        ),
        key=len,
    )
    theirs = dict(re.findall(r"(--[a-z-]+):\s*([^;]+)", root))

    page = live.get("start").decode()
    ours = dict(re.findall(r"(--[a-z-]+):\s*([^;]+);", page))

    checked = 0
    for token, value in ours.items():
        if token in theirs:
            assert value.strip() == theirs[token].strip(), (
                f"{token} is {value.strip()} here and {theirs[token].strip()} in the editor"
            )
            checked += 1
    assert checked >= 10, (
        f"only {checked} tokens compared; the page stopped using theirs"
    )


def test_every_new_button_has_a_tile_to_draw(live: LiveHost):
    """An editor that can create has to have a mark, or New draws a blank.

    The page builds each button's icon as `<use href="#tile-{name}">` from the
    name the host handed it. A reference to a symbol that is not there renders
    nothing at all -- no error, no console message, an empty 28px square -- so
    a fifth editor, or a renamed one, would go out looking finished. The brand
    has a tile for three of the four and Diagrams creates nothing, which is the
    only reason this passes today.
    """
    page = live.get("start").decode()
    creates = [app["name"] for app in live.json("apps") if app["creates"]]
    assert creates, "no editor can create anything; the page has nothing to show"
    for name in creates:
        assert f'id="tile-{name}"' in page, f"New offers {name} and has no tile for it"


def test_the_start_page_does_not_follow_the_system_theme(live: LiveHost):
    """Because the editor does not.

    Measured: the editor renders theme-light whatever the OS is set to, and
    persists a theme only once the user changes one. A dark start window beside
    a light editor is worse than no dark mode.
    """
    page = live.get("start").decode()
    assert "@media (prefers-color-scheme" not in page


def test_the_start_page_is_told_which_editors_can_make_something(live: LiveHost):
    listed = {app["name"]: app for app in live.json("apps")}
    assert listed["tables"]["kind"] == "Spreadsheet"
    assert listed["tables"]["doctype"] == "cell"
    # Diagrams is a viewer: offering New for it would promise what x2t refuses.
    assert listed["diags"]["creates"] is False
    assert listed["words"]["creates"] is True


def test_the_start_page_can_say_where_the_payload_came_from(live: LiveHost):
    info = live.json("payload")
    assert info["root"] == str(live.host.payload)
    assert info["origin"]


@pytest.mark.parametrize(
    ("doctype", "suffix"), [("word", ".docx"), ("cell", ".xlsx"), ("slide", ".pptx")]
)
def test_new_makes_the_kind_of_document_that_was_asked_for(
    live: LiveHost, doctype: str, suffix: str
):
    """The start window asks for a spreadsheet from a session showing a docx."""
    assert live.post(f"new?type={doctype}")[0] == 200
    # In serve mode the blank is converted in place; the session's Editor.bin
    # is the only evidence, and it has to be the one for that editor.
    assert live.host.editor_bin.stat().st_size > 0
    assert (
        live.host.blank_for(next(a for a in apps.ALL if a.doctype == doctype)).suffix
        == suffix
    )


# --- opening things ---------------------------------------------------------


def test_opening_a_document_puts_it_in_the_list_the_editor_fetches(live: LiveHost):
    entries = live.json("recents")
    assert [e["path"] for e in entries] == [str(live.document)]
    # id comes straight back to us on open, so it has to be the path.
    assert entries[0]["id"] == entries[0]["path"]


def test_a_listed_document_can_be_opened(live: LiveHost, tmp_path):
    """With no window to open it in, the one window takes it -- `libera --serve`."""
    other = tmp_path / "other.docx"
    other.write_bytes(live.document.read_bytes())
    recents.remember_recent(other)

    status, body = live.post("open-recent", json.dumps({"id": str(other)}).encode())

    assert status == 200
    assert json.loads(body) == {"opened": True, "here": True}
    assert live.json("current")["path"] == str(other)


def test_file_new_converts_the_blank_the_payload_ships(live: LiveHost):
    assert live.post("new")[0] == 200
    assert live.host.editor_bin.stat().st_size > 0
