"""Prepare every edition of the site for Zensical, and then its root.

Each language in zensical.toml's [[project.extra.alternate]] list is an edition
under its own /<lang>/, English first. English is src/, configured by
zensical.toml and built to site/en/. Every other edition gets:

- its pages, translated, in i18n/<lang>/. They are every page of src/ except
  develop/, which is English-only, and the two sets have to match: the
  language selector (src/assets/lang.js) sends a reader to the same path in
  the other edition;
- a copy of src/assets/, since Zensical does not follow a symlinked directory;
- zensical.<lang>.toml, generated from zensical.toml with that edition's
  paths, language and strings, and a nav whose Developers tab links to the
  English section.

Every edition also gets its News section, from news/<lang>/. A post is
news/<lang>/YYYY-MM-DD-slug.md: YAML front matter with a `date` and a
`description`, then a `# Title`. A translated post keeps the English file name,
and draft-*.md is left out, so a post is published by renaming it. Each post is
written out with its date under the title, beside an index of them all, newest
first, and the News entry of the edition's nav lists them.

The root of the site belongs to no edition, and `--site-root` writes it once
they are all built: see write_site_root.

What each edition says in its own language is in editions.toml. Everything this
writes is gitignored, except the News entry of zensical.toml's nav.

`make build`, `make serve` and `make check` run it. On its own:

    uv run --project .. python preprocess.py
    uv run --project .. python preprocess.py --site-root     # after the builds
"""

from __future__ import annotations

import datetime as dt
import json
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn

import tomllib
import yaml

DOCS = Path(__file__).parent
CONFIG = DOCS / "zensical.toml"
STRINGS = tomllib.loads((DOCS / "editions.toml").read_text("utf-8"))
ASSETS = DOCS / "src" / "assets"
SITE = DOCS / "site"
CHOOSER = DOCS / "index.html"
# The one section that is not translated. Its tab in the other editions links
# to the English pages at this path.
ENGLISH_ONLY = "develop/"
GENERATED = "<!-- Generated by docs/preprocess.py. The source is in docs/news/. -->\n"
# The News entry of zensical.toml's nav: its opening line, the entries indented
# under it, and its closing line. Rewritten whole, so it is found exactly once.
NEWS_NAV = re.compile(r'    \{ "News" = \[\n(?:        .*\n)*    \]\},\n')
NAV = re.compile(r"^nav = \[\n.*?^\]\n", re.DOTALL | re.MULTILINE)
COPYRIGHT = re.compile(r'^copyright = """.*?"""\n', re.DOTALL | re.MULTILINE)


@dataclass(frozen=True)
class Edition:
    lang: str
    link: str  # its address on the site, /<lang>/
    pages: Path  # its docs_dir
    config: Path

    @property
    def strings(self) -> dict:
        return STRINGS[self.lang]


@dataclass(frozen=True)
class Post:
    slug: str
    date: dt.date
    title: str
    description: str
    front: str
    body: str


def fail(msg: str) -> NoReturn:
    text = f"preprocess: {msg}"
    raise SystemExit(text)


def editions(config: str) -> list[Edition]:
    alternates = tomllib.loads(config)["project"]["extra"]["alternate"]
    links = {a["lang"]: a["link"] for a in alternates}
    if list(links)[:1] != ["en"]:
        fail("zensical.toml's first [[project.extra.alternate]] must be English")
    for lang, link in links.items():
        if link != f"/{lang}/":
            fail(f"the {lang} edition's link is {link}, and should be /{lang}/")
    missing = [lang for lang in links if lang not in STRINGS]
    if missing:
        fail(f"editions.toml has no section for {', '.join(missing)}")
    return [
        Edition("en", links["en"], DOCS / "src", CONFIG),
        *(
            Edition(lang, link, DOCS / "i18n" / lang, DOCS / f"zensical.{lang}.toml")
            for lang, link in list(links.items())[1:]
        ),
    ]


# --- news -----------------------------------------------------------------------


def read(path: Path) -> Post:
    text = path.read_text("utf-8")
    front, found, body = text.removeprefix("---\n").partition("\n---\n")
    if not text.startswith("---\n") or not found:
        fail(f"{path} has no front matter")
    meta = yaml.safe_load(front) or {}
    if not isinstance(meta.get("date"), dt.date):
        fail(f"{path} needs `date: YYYY-MM-DD`")
    title = re.search(r"^# (.+)$", body, re.MULTILINE)
    if not title:
        fail(f"{path} has no `# Title` line")
    return Post(
        path.stem,
        meta["date"],
        title.group(1).strip(),
        meta.get("description", ""),
        front,
        body,
    )


def when(day: dt.date, strings: dict) -> str:
    month = strings["months"][day.month - 1]
    return strings["date"].format(day=day.day, month=month, year=day.year)


def publish_news(edition: Edition) -> list[Post]:
    """Write the edition's news pages, and return its posts, newest first."""
    strings = edition.strings
    sources = sorted((DOCS / "news" / edition.lang).glob("*.md"))
    posts = [read(p) for p in sources if not p.name.startswith("draft-")]
    posts.sort(key=lambda p: p.date, reverse=True)

    out = edition.pages / "news"
    shutil.rmtree(out, ignore_errors=True)
    out.mkdir(parents=True)
    for post in posts:
        heading = f"# {post.title}"
        dated = f"{heading}\n\n*{when(post.date, strings)}*"
        body = post.body.replace(heading, dated, 1)
        text = f"---\n{post.front}\n---\n{GENERATED}{body}"
        (out / f"{post.slug}.md").write_text(text, "utf-8")

    lines = [f"# {strings['news_title']}", "", GENERATED, strings["news_intro"], ""]
    for post in posts:
        lines += [
            f"## [{post.title}]({post.slug}.md)",
            "",
            f"*{when(post.date, strings)}*. {post.description}",
            "",
        ]
    (out / "index.md").write_text("\n".join(lines), "utf-8")
    return posts


def news_nav(edition: Edition, posts: list[Post]) -> list[dict]:
    return [
        {edition.strings["all_news"]: "news/index.md"},
        *({p.title: f"news/{p.slug}.md"} for p in posts),
    ]


# --- nav, as TOML -------------------------------------------------------------------


def toml_entry(entry: dict, indent: str) -> str:
    ((label, value),) = entry.items()
    # json.dumps writes a valid TOML basic string, quotes and all.
    key = json.dumps(label, ensure_ascii=False)
    if isinstance(value, str):
        return f"{indent}{{ {key} = {json.dumps(value)} }},"
    inner = "\n".join(toml_entry(child, indent + "    ") for child in value)
    return f"{indent}{{ {key} = [\n{inner}\n{indent}]}},"


def toml_nav(nav: list[dict]) -> str:
    return "nav = [\n" + "\n".join(toml_entry(e, "    ") for e in nav) + "\n]\n"


def paths(value: str | list) -> list[str]:
    if isinstance(value, str):
        return [value]
    return [p for child in value for v in child.values() for p in paths(v)]


def translate_nav(english: list[dict], edition: Edition, news: list[dict]) -> list:
    labels = edition.strings["nav"]
    english_only = f"/en/{ENGLISH_ONLY}"

    def t(label: str) -> str:
        if label not in labels:
            fail(f"editions.toml: [{edition.lang}.nav] has no {json.dumps(label)}")
        return labels[label]

    out: list[dict] = []
    for entry in english:
        ((label, value),) = entry.items()
        if label == "News":
            out.append({t(label): news})
        elif all(p.startswith(ENGLISH_ONLY) for p in paths(value)):
            out.append({t(label): english_only})
        elif isinstance(value, str):
            out.append({t(label): value})
        else:
            out.append({t(label): [{t(k): v} for c in value for k, v in c.items()]})
    return out


def listed(config: Path) -> list[str]:
    """Every path in the nav of a config, read back as the site will read it."""
    nav = tomllib.loads(config.read_text("utf-8"))["project"]["nav"]
    return [p for entry in nav for v in entry.values() for p in paths(v)]


# --- one edition --------------------------------------------------------------------


def pages(root: Path) -> set[str]:
    names = (p.relative_to(root).as_posix() for p in root.rglob("*.md"))
    return {n for n in names if not n.startswith(("news/", ENGLISH_ONLY))}


def replace_once(pattern: str | re.Pattern, new: str, text: str) -> str:
    regex = re.compile(re.escape(pattern) if isinstance(pattern, str) else pattern)
    if len(regex.findall(text)) != 1:
        fail(f"expected one {regex.pattern!r} in zensical.toml")
    return regex.sub(lambda _: new, text)


def edition_config(english: str, nav: list[dict], edition: Edition) -> str:
    lang, s = edition.lang, edition.strings
    dark = json.dumps(s["dark"], ensure_ascii=False)
    light = json.dumps(s["light"], ensure_ascii=False)
    text = english
    for old, new in [
        ('docs_dir = "src"', f'docs_dir = "i18n/{lang}"'),
        ('site_dir = "site/en"', f'site_dir = "site/{lang}"'),
        ('language = "en"', f'language = "{lang}"'),
        ('toggle.name = "Switch to dark mode"', f"toggle.name = {dark}"),
        ('toggle.name = "Switch to light mode"', f"toggle.name = {light}"),
    ]:
        text = replace_once(old, new, text)
    url = tomllib.loads(english)["project"]["site_url"]
    if not url.endswith("/en/"):
        fail(f"zensical.toml's site_url is {url}, and should end in /en/")
    root = url.removesuffix("en/")
    text = replace_once(
        re.compile(r"^site_url = .*\n", re.MULTILINE),
        f'site_url = "{root}{lang}/"\n',
        text,
    )
    description = json.dumps(s["site_description"], ensure_ascii=False)
    text = replace_once(
        re.compile(r"^site_description = .*\n", re.MULTILINE),
        f"site_description = {description}\n",
        text,
    )
    text = replace_once(COPYRIGHT, f'copyright = """{s["copyright"]}"""\n', text)
    text = replace_once(NAV, toml_nav(nav), text)
    header = (
        "# Generated by preprocess.py from zensical.toml "
        f"and editions.toml [{lang}].\n\n"
    )
    return header + text


def publish_english(en: Edition, english: str) -> tuple[str, list[Post]]:
    """English's news, and zensical.toml with its News entry to match."""
    posts = publish_news(en)
    if len(NEWS_NAV.findall(english)) != 1:
        fail('expected one `{ "News" = [` entry in the nav of zensical.toml')
    news = toml_entry({"News": news_nav(en, posts)}, "    ") + "\n"
    english = NEWS_NAV.sub(lambda _: news, english)
    CONFIG.write_text(english, "utf-8")
    return english, posts


def publish_edition(edition: Edition, english: str, en_posts: list[Post]) -> list:
    """Everything one edition needs, and what is wrong with it."""
    problems = []
    expected, have = pages(DOCS / "src"), pages(edition.pages)
    for name in sorted(expected - have):
        problems.append(f"i18n/{edition.lang}/{name} is missing")
    for name in sorted(have - expected):
        problems.append(f"i18n/{edition.lang}/{name} has no English page")

    shutil.rmtree(edition.pages / "assets", ignore_errors=True)
    shutil.copytree(ASSETS, edition.pages / "assets")

    posts = publish_news(edition)
    for slug in sorted({p.slug for p in en_posts} ^ {p.slug for p in posts}):
        problems.append(f"news/{edition.lang}/ and news/en/ differ on {slug}")

    english_nav = tomllib.loads(english)["project"]["nav"]
    nav = translate_nav(english_nav, edition, news_nav(edition, posts))
    edition.config.write_text(edition_config(english, nav, edition), "utf-8")
    return problems


# --- the site root ------------------------------------------------------------------
#
# Nothing is built at the root, since every edition has its own /<lang>/. What
# is there is written once they are all built:
#
# - index.html, the chooser: a link to every edition, and a script that goes to
#   the one chosen last time (a cookie lang.js sets) or, failing that, the
#   first the browser asks for;
# - a redirect at every address the English pages had when they were the root,
#   which were published: the README on PyPI, CHANGES.md, links people saved;
#   and at two addresses from before those;
# - src/assets/, where the 0.3.0 README on PyPI shows its screenshots from.

# Addresses from before main/ existed, and where their pages went.
MOVED = {"guide/install/": "main/install/", "guide/status/": "main/status/"}
REDIRECT = """<!doctype html>
<meta charset="utf-8">
<title>Moved</title>
<link rel="canonical" href="{to}">
<script>location.replace("{to}" + location.hash)</script>
<meta http-equiv="refresh" content="0; url={to}">
<p>This page moved to <a href="{to}">{to}</a>.</p>
"""


def address(page: str) -> str:
    """Where Zensical publishes a page: guide/documents.md at guide/documents/."""
    stem = page.removesuffix(".md")
    if stem == "index":
        return ""
    return stem.removesuffix("index") if stem.endswith("/index") else f"{stem}/"


def write_site_root(all_editions: list[Edition]) -> None:
    chooser = CHOOSER.read_text("utf-8")
    for edition in all_editions:
        if f'href="{edition.lang}/"' not in chooser:
            fail(f"index.html has no link to the {edition.lang} edition")
    SITE.mkdir(exist_ok=True)
    (SITE / "index.html").write_text(chooser, "utf-8")

    en = all_editions[0]
    names = (p.relative_to(en.pages).as_posix() for p in en.pages.rglob("*.md"))
    moved = {address(n): address(n) for n in names} | MOVED
    del moved[""]  # the root: the chooser now
    langs = {e.lang for e in all_editions}
    for old, new in moved.items():
        if old.split("/")[0] in langs:
            fail(f"/{old} would be a redirect inside the {old[:2]} edition")
        out = SITE / old / "index.html"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(REDIRECT.format(to=f"{en.link}{new}"), "utf-8")

    shutil.copytree(ASSETS, SITE / "assets", dirs_exist_ok=True)
    print(f"preprocess: site root, and {len(moved)} redirects to {en.link}")


def main() -> None:
    en, *others = editions(CONFIG.read_text("utf-8"))
    if sys.argv[1:] == ["--site-root"]:
        write_site_root([en, *others])
        return
    # English first: its nav, News included, is what every edition translates.
    english, en_posts = publish_english(en, CONFIG.read_text("utf-8"))
    problems = [p for e in others for p in publish_edition(e, english, en_posts)]

    # Stale configs, from an edition that has since been dropped, would build.
    wanted = {e.config for e in others}
    for config in DOCS.glob("zensical.*.toml"):
        if config not in wanted:
            config.unlink()

    # Read every nav back as TOML: what the site builds from, not what was
    # written. Each must list exactly its own news.
    for edition in (en, *others):
        news_paths = [p for p in listed(edition.config) if p.startswith("news/")]
        own = {f"news/{p.stem}.md" for p in (edition.pages / "news").glob("*.md")}
        assert set(news_paths) == own, (edition.lang, news_paths)

    if problems:
        fail("the editions do not match:\n  " + "\n  ".join(problems))
    langs = ", ".join(e.lang for e in (en, *others))
    print(f"preprocess: {langs}; {len(en_posts)} news post(s) each")


if __name__ == "__main__":
    main()
